name: my_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  date_format: ^2.0.9
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Aleo
      fonts:
        - asset: assets/fonts/Aleo-VariableFont_wght.ttf
